In [49]:
import pandas as pd
import os
import datetime

In [50]:
# Define the folder path where the CSV files are located
folder_path = "CitibikeDataFiles"

# Get the list of file names in the folder
file_names = os.listdir(folder_path)

# Create an empty DataFrame to store the merged data
merged_data = pd.DataFrame()

# Loop through each file in the folder
for file_name in file_names:
    # Check if the file is a CSV file
    if file_name.endswith(".csv"):
        # Read the CSV file into a DataFrame
        file_path = os.path.join(folder_path, file_name)
        df = pd.read_csv(file_path)
        
        # Append the DataFrame to the merged_data
        merged_data = merged_data.append(df, ignore_index=True)

# Write the merged data to a new CSV file
merged_file_path = "MergedCitibikeData.csv"
merged_data.to_csv(merged_file_path, index=False)

print("Merged data saved to", merged_file_path)

/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/761664890.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_data = merged_data.append(df, ignore_index=True)

Merged data saved to MergedCitibikeData.csv

In [51]:
# Define the file path of the merged data
merged_file_path = "MergedCitibikeData.csv"

# Load the merged data into a pandas DataFrame
merged_data = pd.read_csv(merged_file_path)

# Display the DataFrame
merged_data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,156,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1
1,143,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1
2,305,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2
3,1097,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1
4,277,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1

In [52]:
# Convert tripduration from seconds to minutes
merged_data['tripduration'] = merged_data['tripduration'] / 60

# Remove durations less than 100 seconds, 1.67 minutes is equivalent to 100 seconds
merged_data = merged_data[merged_data['tripduration'] >= 1.67]  

# Define the bin edges and labels
bin_edges = [0, 5, 10, 20, 30, 40, 50, 60, 90, 120, float('inf')]
bin_labels = [
    "Less than or equal to 5 mins",
    "More than 5 mins",
    "More than 10 mins",
    "More than 20 mins",
    "More than 30 mins",
    "More than 40 mins",
    "More than 50 mins",
    "More than 1 hour",
    "More than 1.5 hours",
    "More than 2 hours"
]

# Create a new column 'tripduration_bins' with the bin labels
merged_data['tripduration_bins'] = pd.cut(merged_data['tripduration'], bins=bin_edges, labels=bin_labels)


# Display the DataFrame
merged_data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,tripduration_bins
0,2.600000,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1,Less than or equal to 5 mins
1,2.383333,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1,Less than or equal to 5 mins
2,5.083333,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2,More than 5 mins
3,18.283333,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1,More than 10 mins
4,4.616667,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1,Less than or equal to 5 mins

In [53]:
# Split "starttime" column into date and time
merged_data[['start_date', 'start_time']] = merged_data['starttime'].str.split(' ', 1, expand=True)

# Split "stoptime" column into date and time
merged_data[['stop_date', 'stop_time']] = merged_data['stoptime'].str.split(' ', 1, expand=True)

# Display the DataFrame
merged_data.head()

/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/17351207.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  merged_data[['start_date', 'start_time']] = merged_data['starttime'].str.split(' ', 1, expand=True)
/var/folders/c6/f4lv068572x0t6lvnvn2yjyc0000gn/T/ipykernel_77056/17351207.py:5: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  merged_data[['stop_date', 'stop_time']] = merged_data['stoptime'].str.split(' ', 1, expand=True)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,tripduration_bins,start_date,start_time,stop_date,stop_time
0,2.600000,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1,Less than or equal to 5 mins,2020-10-01,00:02:40.2600,2020-10-01,00:05:17.0140
1,2.383333,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1,Less than or equal to 5 mins,2020-10-01,00:02:53.5020,2020-10-01,00:05:16.9650
2,5.083333,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2,More than 5 mins,2020-10-01,00:04:31.3160,2020-10-01,00:09:36.3840
3,18.283333,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1,More than 10 mins,2020-10-01,00:05:18.3680,2020-10-01,00:23:36.1240
4,4.616667,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1,Less than or equal to 5 mins,2020-10-01,00:09:17.5990,2020-10-01,00:13:55.5150

In [54]:
# Map gender values to corresponding labels
gender_mapping = {0: 'Unknown', 1: 'Male', 2: 'Female'}
merged_data['gender_label'] = merged_data['gender'].map(gender_mapping)

# Display the DataFrame
merged_data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,bikeid,usertype,birth year,gender,tripduration_bins,start_date,start_time,stop_date,stop_time,gender_label
0,2.600000,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,...,42293,Subscriber,1996,1,Less than or equal to 5 mins,2020-10-01,00:02:40.2600,2020-10-01,00:05:17.0140,Male
1,2.383333,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,...,44740,Subscriber,1998,1,Less than or equal to 5 mins,2020-10-01,00:02:53.5020,2020-10-01,00:05:16.9650,Male
2,5.083333,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,...,41369,Subscriber,1988,2,More than 5 mins,2020-10-01,00:04:31.3160,2020-10-01,00:09:36.3840,Female
3,18.283333,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,...,42285,Customer,2001,1,More than 10 mins,2020-10-01,00:05:18.3680,2020-10-01,00:23:36.1240,Male
4,4.616667,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,...,45231,Subscriber,1965,1,Less than or equal to 5 mins,2020-10-01,00:09:17.5990,2020-10-01,00:13:55.5150,Male

In [55]:
# Calculate the current year
current_year = datetime.datetime.now().year

# Calculate the age for each row
merged_data['age'] = current_year - merged_data['birth year']

# Display the DataFrame
merged_data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,usertype,birth year,gender,tripduration_bins,start_date,start_time,stop_date,stop_time,gender_label,age
0,2.600000,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,...,Subscriber,1996,1,Less than or equal to 5 mins,2020-10-01,00:02:40.2600,2020-10-01,00:05:17.0140,Male,27
1,2.383333,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,...,Subscriber,1998,1,Less than or equal to 5 mins,2020-10-01,00:02:53.5020,2020-10-01,00:05:16.9650,Male,25
2,5.083333,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,...,Subscriber,1988,2,More than 5 mins,2020-10-01,00:04:31.3160,2020-10-01,00:09:36.3840,Female,35
3,18.283333,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,...,Customer,2001,1,More than 10 mins,2020-10-01,00:05:18.3680,2020-10-01,00:23:36.1240,Male,22
4,4.616667,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,...,Subscriber,1965,1,Less than or equal to 5 mins,2020-10-01,00:09:17.5990,2020-10-01,00:13:55.5150,Male,58

In [56]:
# Convert start_date column to datetime format
merged_data['start_date'] = pd.to_datetime(merged_data['start_date'])

# Define the seasons based on date ranges in the United States
seasons = {
    'Winter': ((merged_data['start_date'].dt.month >= 1) & (merged_data['start_date'].dt.month <= 2)) |
              ((merged_data['start_date'].dt.month == 12) & (merged_data['start_date'].dt.day >= 21)),
    'Spring': (merged_data['start_date'].dt.month >= 3) & (merged_data['start_date'].dt.month <= 5),
    'Summer': (merged_data['start_date'].dt.month >= 6) & (merged_data['start_date'].dt.month <= 8),
    'Fall': (merged_data['start_date'].dt.month >= 9) & (merged_data['start_date'].dt.month <= 11)
}

# Assign the season based on the date ranges
merged_data['season'] = pd.Series(dtype='object')

for season, condition in seasons.items():
    merged_data.loc[condition, 'season'] = season

# Display the updated DataFrame
merged_data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,birth year,gender,tripduration_bins,start_date,start_time,stop_date,stop_time,gender_label,age,season
0,2.600000,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,...,1996,1,Less than or equal to 5 mins,2020-10-01,00:02:40.2600,2020-10-01,00:05:17.0140,Male,27,Fall
1,2.383333,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,...,1998,1,Less than or equal to 5 mins,2020-10-01,00:02:53.5020,2020-10-01,00:05:16.9650,Male,25,Fall
2,5.083333,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,...,1988,2,More than 5 mins,2020-10-01,00:04:31.3160,2020-10-01,00:09:36.3840,Female,35,Fall
3,18.283333,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,...,2001,1,More than 10 mins,2020-10-01,00:05:18.3680,2020-10-01,00:23:36.1240,Male,22,Fall
4,4.616667,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,...,1965,1,Less than or equal to 5 mins,2020-10-01,00:09:17.5990,2020-10-01,00:13:55.5150,Male,58,Fall

In [57]:
# Define the output file path
output_file_path = "Cleaned_CitiBikeData.csv"

# Export the merged_data DataFrame to CSV
merged_data.to_csv(output_file_path, index=False)

print("Data exported to", output_file_path)

Data exported to Cleaned_CitiBikeData.csv